version: "2"

run:
  tests: true

linters:
  enable:
    - funlen
    - goconst
    - gocritic
    - misspell
    - unconvert
    - unparam

  settings:
    dupl:
      threshold: 100

    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (github.com/jackc/pgx/v5.Tx).Rollback
        - (net/http.ResponseWriter).Write
        - fmt.Scanln

    funlen:
      lines: -1
      statements: -1

    goconst:
      min-occurrences: 3

    gocritic:
      disabled-checks:
        - ifElseChain
      enabled-checks:
        - boolExprSimplify
        - commentedOutCode
        - unnamedResult

  exclusions:
    generated: lax

    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - linters:
          - dupl
          - funlen
          - gocyclo
        path: _test\.go

    paths:
      - ui
      - bin
      - .cache
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/ripta/electron_microscope

  exclusions:
    generated: lax
    paths:
      - ui
      - bin
      - .cache
      - third_party$
      - builtin$
      - examples$
